blog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    # path('post/<int:pk>/', views.detail, name='detail'),
    path('post/<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('archives/<int:year>/<int:month>/', views.archives, name='archives'),
    path('archives/<int:year>/<int:month>/', views.ArchivesView.as_view(), name='archives'),
    # path('category/<int:pk>/', views.category, name='category'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tag/<int:pk>/', views.TagView.as_view(), name='tag'),
]

comments/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'comments'
urlpatterns = [
    path('post/<int:post_pk>', views.post_comment, name='post_comment'),
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('comment/',include('comments.urls')),
]

blog/models.py
import markdown
from django.db import models
from django.contrib.auth.models import User
from django.utils.html import strip_tags

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=14)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=40)
    excerpt = models.CharField(max_length=300, blank=True)
    body = models.TextField()
    created_time = models.DateField()
    modified_time = models.DateField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_time']
    
    def update_view(self):
        self.views+=1
        self.save(update_fields=['views'])
    
    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=['markdown.extensions.extra', 'markdown.extensions.codehilite'])
            self.excerpt = strip_tags(md.convert(self.body))[:250] + '...'
        super(Post, self).save(*args, **kwargs)

comments/models.py
from django.db import models

# Create your models here.


class Comment(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField(max_length=40)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now=True)
    post = models.ForeignKey('blog.post', on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]
    
    class Meta:
        ordering = ['-created_time']

comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'text']

blog/views.py
import markdown
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Post, Category, Tag
from comments.forms import CommentForm

# Create your views here.

# 改用下面类方法实现
# def index(request):
#     # return HttpResponse('hello blog')
#     post_list = Post.objects.all()
#     return render(request, 'blog/index.html', {'post_list':post_list})
class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    contex_object_name = 'post_list'
    paginate_by =5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)
        return context
    
    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        page_number = page.number
        total_pages = paginator.num_pages
        page_range = paginator.page_range
        right = page_range[page_number:page_number + 2]
        left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
        if right:
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        if left:
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        data = {
            'left':left,
            'right':right,
            'left_has_more':left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last':last,
        }
        return data




# 改用下面类方法实现
# def archives(request, year, month):
#     post_list = Post.objects.filter(created_time__year=year, created_time__month=month)
#     return render(request, 'blog/index.html', {'post_list':post_list})
class ArchivesView(IndexView):
    def get_queryset(self):
        return super(ArchivesView, self).get_queryset().filter(created_time__year=self.kwargs.get('year'), created_time__month=self.kwargs.get('month'))


# 改用下面类方法实现
# def category(request, pk):
#     cate = get_object_or_404(Category, pk=pk)
#     post_list = Post.objects.filter(category=cate)
#     return render(request, 'blog/index.html', {'post_list':post_list})
class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


class TagView(IndexView):
    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)



# 改用下面类方法实现
# def detail(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     post.update_view()
#     post.body = markdown.markdown(post.body, extensions=['markdown.extensions.extra', 'markdown.extensions.codehilite', 'markdown.extensions.toc'])
#     form = CommentForm()
#     comment_list = post.comment_set.all()
#     return render(request, 'blog/detail.html', {'post':post, 'form':form, 'comment_list':comment_list})
class DetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    contex_object_name = 'post'

    def get(self, request, *args, **kwargs):
        response = super(DetailView, self).get(request, *args, **kwargs)
        self.object.update_view()
        return response
    
    def get_object(self, queryset=None):
        post = super(DetailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=['markdown.extensions.extra', 'markdown.extensions.codehilite', 'markdown.extensions.toc'])
        post.body = md.convert(post.body)
        post.toc = md.toc
        return post
    
    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({'form':form, 'comment_list':comment_list})
        return context

comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from blog.models import Post
from .models import Comment
from .forms import CommentForm

# Create your views here.

def post_comment(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == 'POST':
        form= CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return HttpResponseRedirect(reverse('blog:detail', args=(post_pk, )))
        else:
            comment_list = post.comment_set.all()
            return render(request, 'blog/detail.html', {'post':post, 'form':form, 'comment_list':comment_list})
    else:
        return HttpResponseRedirect(reverse('blog:detail', args=(post_pk, )))

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>Reedo</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/' %}jquery-2.1.3.min.js"></script>
    <script src="{% static 'blog/js/' %}bootstrap.min.js"></script>
    <script src="{% static 'blog/js/' %}pace.min.js"></script>
    <script src="{% static 'blog/js/' %}modernizr.custom.js"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Reedo</b></a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>


<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>

            <aside class="col-md-4">
                {% block aside %}
                {% endblock aside %}
                
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                            <li>
                                <a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count"> ({{ category.num_posts }})</span></a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as archives_list %}
                    <ul>
                        {% for date in archives_list %}
                            <li>
                                <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }}年{{ date.month }}月</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% get_tags as tag_list %}
                        {% for tag in tag_list %}
                            <li>
                                <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }} ({{ tag.num_posts }})</a>
                            </li>
                        {% endfor %}
                        
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - Reedo.Inc
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">首页</a></li>
            <li><a href="{% url 'blog:index' %}">博客</a></li>
            <li><a href="{% url 'blog:index' %}">关于</a></li>
            <li><a href="{% url 'blog:index' %}">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/' %}script.js"></script>

</body>
</html>

templates/blog/detail.html
{% extends "base.html" %}

{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">分类：{{ post.category }}</a>&nbsp;&nbsp;&nbsp;</span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">发布时间：{{ post.created_time }}</time></a>&nbsp;&nbsp;&nbsp;</span>
                <span class="post-author"><a href="#">作者：{{ post.author }}</a>&nbsp;&nbsp;&nbsp;</span>
                <span class="comments-link"><a href="#">评论：{{ post.comment_set.count }}&nbsp;&nbsp;&nbsp;</a></span>
                <span class="views-count"><a href="#">阅读：{{ post.views }}</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
                {{ post.body|safe }}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            <div class="row">
                <div class="col-md-4">
                    <label for="id_name">名字：</label>
                    {{ form.name }}
                    <!-- <input type="text" id="id_name" name="name" required> -->
                </div>
                <div class="col-md-4">
                    <label for="id_email">邮箱：</label>
                    {{ form.email }}
                    <!-- <input type="email" id="id_email" name="email" required> -->
                </div>
                <div class="col-md-12">
                    <label for="id_comment">评论：</label>
                    {{ form.text }}
                    <!-- <textarea name="comment" id="id_comment" required></textarea> -->
                    {% csrf_token %}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{ comment.created_time }}</time>
                        <div class="text">
                            {{ comment.text }}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}


{% block aside %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        {{ post.toc|safe }}
    </div>
{% endblock aside %}

templates/blog/index.html
{% extends "base.html" %}

{% block main %}
    {% for post in post_list %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">分类：{{ post.category }}</a>&nbsp;&nbsp;&nbsp;</span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">发布时间：{{ post.created_time }}</time></a>&nbsp;&nbsp;&nbsp;</span>
                <span class="post-author"><a href="#">作者：{{ post.author }}</a>&nbsp;&nbsp;&nbsp;</span>
                <span class="comments-link"><a href="#">评论：{{ post.comment_set.count }}&nbsp;&nbsp;&nbsp;</a></span>
                <span class="views-count"><a href="#">阅读：{{ post.views }}</a></span>

            </div>
        </header>
        <div class="entry-content clearfix">
            <p>{{ post.excerpt }}</p>
            <div class="read-more cl-effect-14">
                <a href="{% url 'blog:detail' post.pk %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
    {% endfor %}

    <!-- 简单分页实现 -->
    <!-- {% if is_paginated %}
    <div class="pagination-simple">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">上一页 </a>
        {% endif %}
        <span class="current"> 第{{ page_obj.number }}页/共{{ paginator.num_pages }}页 </span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"> 下一页</a>
        {% endif %}
    </div>
    {% endif %} -->

    {% if is_paginated %}
        <div class="pagination">
            <ul>
                {% if first %}
                    <li><a href="?page=1">1</a></li>
                {% endif %}
                {% if left %}
                    {% if left_has_more %}
                        <li><a href="">...</a></li>
                    {% endif %}
                    {% for i in left %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endfor %}
                {% endif %}
                <li class="current"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                {% if right %}
                    {% for i in right %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endfor %}
                    {% if right_has_more %}
                        <li><a href="">...</a></li>
                    {% endif %}
                {% endif %}
                {% if last %}
                    <li><a href="?page={{ paginator.num_pages }}">1</a></li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
{% endblock main %}